language: c

addons:
  apt:
    packages:
      - valgrind
      - cppcheck

install:
  - gem install ceedling

script:
  - mkdir test/support && mkdir build
  - cppcheck src/list.c src/list.h test/test_list.c
  - ceedling test:all && valgrind --leak-check=full --error-exitcode=1 build/test/out/test_list.out > /dev/null
